version: 0.7.1
title: pyros.sh
description: Hi there, I'm Peter John, a fullstack developer from Bangalore, India.
url: https://pyros.sh
image: https://pyros.sh/assets/lighthouse.png
author: Peter John
keywords: peter john,pyros.sh,full stack developer,bangalore,india
languages: [en]
