version: 0.1.1
title: pyros.sh
description: Hi there, I'm Peter John, a fullstack developer from Bangalore, India.
url: https://pyros.sh
image: https://pyros.sh/assets/icon.png
author: pyros.sh
keywords: pyros2097,pyros.sh,full stack developer,bangalore,india
lang: en
