name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Add BunnyCDN fallback
        run: |
          mkdir -p ./public/bunnycdn_errors
          cp ./public/404/index.html ./public/bunnycdn_errors/404.html
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /
          exclude: assets/audio*
            - assets/audio/**/*
      - name: Purge
        run: |
          curl -i --fail -X POST -H "AccessKey: ${{ secrets.BCDN_API_TOKEN }}" -H "Content-Length: 0" https://api.bunny.net/pullzone/392667/purgeCache
