name: 🚀 Deploy website on push
on:
  push:
    branches:
      - master
jobs:
  build-and-test-and-push:
    runs-on: ubuntu-latest
    name: Build and test and push
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build-prod
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: .git*
            - **.git*
            - .git*/**
            - **/.git*/**
            - node_modules/**
            - node_modules/**/*
            - assets/audio/**/*
            - package.json
            - package-lock.json
            - tailwind.config.js