name: 🚀 Deploy website on push
on:
  push:
    branches:
      - master
jobs:
  build-and-test-and-push:
    runs-on: ubuntu-latest
    name: Build and test and push
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /
          exclude: assets/audio*
            - assets/audio/**/*
